version: "2"

services:
  postgres:
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - localhost
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./postgres.conf:/etc/postgresql/postgresql.conf

networks:
  localhost:
